//
//  ListOfRecipesInteractor.swift
//  BuildARecipesBook
//
//  Created by Enric Pou Villanueva on 17/05/2019.
//  Copyright (c) 2019 Enric Pou Villanueva. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListOfRecipesInteractor: ListOfRecipesPresenterToInteractorProtocol{
    
    var presenter: ListOfRecipesInteractorToPresenterProtocol?
    var listOfImages: [String] = []
    
    func fetchRecipes() {
        
        APIClient.listOfRecipes { (DTO, error) in
            
            if let dataError = error {
                self.presenter?.errorFechingRecipes(error: dataError)
            } else {
                guard let recipe = DTO?.results else {return}
                self.presenter?.listOfRecipes(recipes: ListOfRecipesModel(results: recipe))
                
                for eachUrlImage in recipe {
                    self.listOfImages.append(eachUrlImage.thumbnail)
                }
            }
        }
    }
}
